### ISSUE TITLE
Submit code

### ISSUE THREAD

**Issue by rubencart** [ameyagodbole/multihop_inference_explanation_regeneration#1]
Hi, are you planning on pushing the actual code for the project in the (near) future? 🙂 Would be much appreciated!

**Comment by mulangonando** [comment]
On my side too, I have been looking out for this code since the workshop

**Comment by rubencart** [comment]
I sent them an email, I'll keep you posted :).

**Comment by ameyagodbole** [comment]
Sorry for the delay. The code and data have been pushed.

I updated the function calls to use the transformers library since huggingface renamed their repository again. If you have any issues with running the code, let me know.

**Comment by rubencart** [comment]
Thank you!
